use std::collections::{BTreeMap, BTreeSet};

use asterism_domain::{
    AnswerCandidate, AnswerCandidateId, AnswerSource, NormalizedAnswer, Question,
    QuestionContentFingerprint, QuestionKind, QuestionSnapshotId, TaskId, UserId,
};
use asterism_storage::{
    AnswerCacheRepository, AnswerCandidateRecord, AnswerCandidateRepository, PriorAnswerEvidence,
    QuestionSnapshot, QuestionSnapshotRepository, StorageError,
};
use chrono::Utc;

#[derive(Clone, Debug)]
pub struct ImportLocalAnswerCandidatesCommand {
    pub owner_id: UserId,
    pub task_id: TaskId,
    pub question_snapshot_id: QuestionSnapshotId,
}

#[derive(Clone, Debug)]
pub struct LocalAnswerCacheService<S> {
    snapshots: S,
}

impl<S> LocalAnswerCacheService<S> {
    pub const fn new(snapshots: S) -> Self {
        Self { snapshots }
    }
}

impl<S> LocalAnswerCacheService<S>
where
    S: QuestionSnapshotRepository + AnswerCandidateRepository + AnswerCacheRepository,
{
    /// Imports direct evidence from exact, unambiguous prior Question matches.
    /// Source attribution and provenance are generated by Core, and repeated
    /// imports of the same source Candidate are idempotent.
    ///
    /// # Errors
    ///
    /// Returns [`LocalAnswerCacheError`] for owner/Task/Snapshot mismatches,
    /// inconsistent persisted evidence, or storage failures.
    pub async fn import(
        &self,
        command: ImportLocalAnswerCandidatesCommand,
    ) -> Result<Vec<AnswerCandidateRecord>, LocalAnswerCacheError> {
        let snapshot = self
            .snapshots
            .find_owned_question_snapshot(command.owner_id, command.question_snapshot_id)
            .await?
            .filter(|snapshot| snapshot.task_id == command.task_id)
            .ok_or(LocalAnswerCacheError::QuestionSnapshotNotFound)?;
        let targets = target_questions_by_fingerprint(&snapshot)?;
        let evidence = self
            .snapshots
            .list_owned_prior_answer_evidence(command.owner_id, command.task_id, snapshot.id)
            .await?;
        let existing = self
            .snapshots
            .list_owned_answer_candidates(command.owner_id, snapshot.id)
            .await?;
        validate_existing(&snapshot, &existing)?;

        let mut source_candidate_ids = BTreeSet::new();
        let mut imported = Vec::new();
        for source in evidence {
            let Some(target) = validate_source(&snapshot, &targets, &source)? else {
                continue;
            };
            if !source_candidate_ids.insert(source.source_candidate.id) {
                return Err(LocalAnswerCacheError::EvidenceInvalid);
            }
            if !answer_matches_question(target, &source.source_candidate.candidate.answer) {
                continue;
            }

            let provenance = local_cache_provenance(&source);
            if existing.iter().any(|record| {
                record.candidate.question_id == target.id
                    && record.candidate.source == AnswerSource::LocalCache
                    && record.candidate.provenance_sanitized == provenance
            }) {
                continue;
            }
            let candidate = AnswerCandidate {
                question_id: target.id,
                source: AnswerSource::LocalCache,
                answer: source.source_candidate.candidate.answer.clone(),
                confidence: source.source_candidate.candidate.confidence,
                explanation: Some("Reused from an exact prior Question match.".to_owned()),
                provenance_sanitized: provenance,
            };
            if candidate.validate().is_err() {
                return Err(LocalAnswerCacheError::EvidenceInvalid);
            }
            imported.push(AnswerCandidateRecord {
                id: AnswerCandidateId::new(),
                question_snapshot_id: snapshot.id,
                candidate,
                created_at: Utc::now(),
            });
        }

        if !imported.is_empty() {
            self.snapshots
                .save_answer_candidate_batch(&imported)
                .await?;
        }
        Ok(imported)
    }
}

fn target_questions_by_fingerprint(
    snapshot: &QuestionSnapshot,
) -> Result<BTreeMap<QuestionContentFingerprint, Vec<&Question>>, LocalAnswerCacheError> {
    let mut ids = BTreeSet::new();
    let mut positions = BTreeSet::new();
    let mut targets = BTreeMap::<QuestionContentFingerprint, Vec<&Question>>::new();
    for question in &snapshot.questions {
        if question.task_id != snapshot.task_id
            || question.validate().is_err()
            || !ids.insert(question.id)
            || !positions.insert(question.position)
        {
            return Err(LocalAnswerCacheError::EvidenceInvalid);
        }
        targets
            .entry(
                question
                    .content_fingerprint()
                    .map_err(|_| LocalAnswerCacheError::EvidenceInvalid)?,
            )
            .or_default()
            .push(question);
    }
    Ok(targets)
}

fn validate_existing(
    snapshot: &QuestionSnapshot,
    existing: &[AnswerCandidateRecord],
) -> Result<(), LocalAnswerCacheError> {
    let question_ids = snapshot
        .questions
        .iter()
        .map(|question| question.id)
        .collect::<BTreeSet<_>>();
    let mut candidate_ids = BTreeSet::new();
    if existing.iter().any(|record| {
        record.question_snapshot_id != snapshot.id
            || !question_ids.contains(&record.candidate.question_id)
            || record.candidate.validate().is_err()
            || !candidate_ids.insert(record.id)
    }) {
        Err(LocalAnswerCacheError::EvidenceInvalid)
    } else {
        Ok(())
    }
}

fn validate_source<'a>(
    target_snapshot: &QuestionSnapshot,
    targets: &'a BTreeMap<QuestionContentFingerprint, Vec<&'a Question>>,
    evidence: &PriorAnswerEvidence,
) -> Result<Option<&'a Question>, LocalAnswerCacheError> {
    let target = targets
        .get(&evidence.question_content_fingerprint)
        .ok_or(LocalAnswerCacheError::EvidenceInvalid)?;
    if target.len() != 1
        || evidence.source_candidate.question_snapshot_id == target_snapshot.id
        || evidence.source_question.task_id != target_snapshot.task_id
        || evidence.source_candidate.candidate.question_id != evidence.source_question.id
        || evidence.source_candidate.candidate.source == AnswerSource::LocalCache
        || evidence.source_candidate.candidate.validate().is_err()
        || evidence.source_question.content_fingerprint().as_ref()
            != Ok(&evidence.question_content_fingerprint)
    {
        return Err(LocalAnswerCacheError::EvidenceInvalid);
    }
    if matches!(
        evidence.source_candidate.candidate.answer,
        NormalizedAnswer::Unknown
    ) {
        return Ok(None);
    }
    Ok(target.first().copied())
}

fn answer_matches_question(question: &Question, answer: &NormalizedAnswer) -> bool {
    match (question.kind, answer) {
        (QuestionKind::SingleChoice, NormalizedAnswer::Selections(values)) => {
            values.len() == 1 && selections_exist(question, values)
        }
        (QuestionKind::MultipleChoice, NormalizedAnswer::Selections(values)) => {
            selections_exist(question, values)
        }
        (QuestionKind::TrueFalse, NormalizedAnswer::Boolean(_))
        | (QuestionKind::FillBlank | QuestionKind::ShortAnswer, NormalizedAnswer::Texts(_)) => true,
        (QuestionKind::Ordering, NormalizedAnswer::Ordering(values)) => {
            values.len() == question.options.len() && selections_exist(question, values)
        }
        _ => false,
    }
}

fn selections_exist(question: &Question, values: &[String]) -> bool {
    let option_ids = question
        .options
        .iter()
        .map(|option| option.id.as_str())
        .collect::<BTreeSet<_>>();
    !values.is_empty()
        && values
            .iter()
            .all(|value| option_ids.contains(value.as_str()))
}

fn local_cache_provenance(evidence: &PriorAnswerEvidence) -> serde_json::Value {
    serde_json::json!({
        "origin": "prior_question_snapshot",
        "source_question_snapshot_id": evidence.source_candidate.question_snapshot_id.to_string(),
        "source_question_id": evidence.source_question.id.to_string(),
        "source_answer_candidate_id": evidence.source_candidate.id.to_string(),
        "source_answer_source": answer_source_name(evidence.source_candidate.candidate.source),
        "question_content_fingerprint": evidence.question_content_fingerprint.as_str(),
    })
}

const fn answer_source_name(source: AnswerSource) -> &'static str {
    match source {
        AnswerSource::Manual => "manual",
        AnswerSource::ProviderNative => "provider_native",
        AnswerSource::ExternalBank => "external_bank",
        AnswerSource::Other => "other",
        AnswerSource::LocalCache => "local_cache",
    }
}

#[derive(Debug, thiserror::Error)]
pub enum LocalAnswerCacheError {
    #[error("question snapshot was not found")]
    QuestionSnapshotNotFound,
    #[error("persisted Question or AnswerCandidate cache evidence is inconsistent")]
    EvidenceInvalid,
    #[error(transparent)]
    Storage(#[from] StorageError),
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use asterism_domain::{AnswerConfidence, ProviderId, QuestionId, QuestionOption};
    use async_trait::async_trait;

    use super::*;

    #[derive(Debug)]
    struct FakeRepository {
        owner_id: UserId,
        snapshot: QuestionSnapshot,
        evidence: Mutex<Vec<PriorAnswerEvidence>>,
        existing: Mutex<Vec<AnswerCandidateRecord>>,
        saved: Mutex<Vec<AnswerCandidateRecord>>,
    }

    #[async_trait]
    impl QuestionSnapshotRepository for FakeRepository {
        async fn save_question_snapshot(
            &self,
            _snapshot: &QuestionSnapshot,
        ) -> Result<(), StorageError> {
            unreachable!("cache imports never create Question snapshots")
        }

        async fn find_owned_question_snapshot(
            &self,
            owner_id: UserId,
            question_snapshot_id: QuestionSnapshotId,
        ) -> Result<Option<QuestionSnapshot>, StorageError> {
            Ok(
                (owner_id == self.owner_id && question_snapshot_id == self.snapshot.id)
                    .then(|| self.snapshot.clone()),
            )
        }

        async fn find_latest_owned_question_snapshot(
            &self,
            _owner_id: UserId,
            _task_id: TaskId,
        ) -> Result<Option<QuestionSnapshot>, StorageError> {
            unreachable!("cache imports require an explicit snapshot")
        }
    }

    #[async_trait]
    impl AnswerCandidateRepository for FakeRepository {
        async fn save_answer_candidate_batch(
            &self,
            candidates: &[AnswerCandidateRecord],
        ) -> Result<(), StorageError> {
            self.saved.lock().unwrap().extend_from_slice(candidates);
            self.existing.lock().unwrap().extend_from_slice(candidates);
            Ok(())
        }

        async fn list_owned_answer_candidates(
            &self,
            owner_id: UserId,
            question_snapshot_id: QuestionSnapshotId,
        ) -> Result<Vec<AnswerCandidateRecord>, StorageError> {
            if owner_id == self.owner_id && question_snapshot_id == self.snapshot.id {
                Ok(self.existing.lock().unwrap().clone())
            } else {
                Ok(Vec::new())
            }
        }
    }

    #[async_trait]
    impl AnswerCacheRepository for FakeRepository {
        async fn list_owned_prior_answer_evidence(
            &self,
            owner_id: UserId,
            task_id: TaskId,
            target_question_snapshot_id: QuestionSnapshotId,
        ) -> Result<Vec<PriorAnswerEvidence>, StorageError> {
            if owner_id == self.owner_id
                && task_id == self.snapshot.task_id
                && target_question_snapshot_id == self.snapshot.id
            {
                Ok(self.evidence.lock().unwrap().clone())
            } else {
                Ok(Vec::new())
            }
        }
    }

    #[tokio::test]
    async fn exact_prior_evidence_is_core_attributed_rebound_and_idempotent() {
        let (service, command) = fixture();
        let imported = service.import(command.clone()).await.unwrap();
        assert_eq!(imported.len(), 1);
        assert_eq!(
            imported[0].candidate.question_id,
            service.snapshots.snapshot.questions[0].id
        );
        assert_eq!(imported[0].candidate.source, AnswerSource::LocalCache);
        assert_eq!(
            imported[0].candidate.answer,
            NormalizedAnswer::Selections(vec!["A".to_owned()])
        );
        assert_eq!(
            imported[0].candidate.provenance_sanitized["origin"],
            "prior_question_snapshot"
        );
        assert_eq!(service.import(command).await.unwrap(), Vec::new());
        assert_eq!(service.snapshots.saved.lock().unwrap().len(), 1);
    }

    #[tokio::test]
    async fn unknown_or_incompatible_evidence_is_not_imported() {
        let (unknown_service, command) = fixture();
        unknown_service.evidence()[0]
            .source_candidate
            .candidate
            .answer = NormalizedAnswer::Unknown;
        assert!(unknown_service.import(command).await.unwrap().is_empty());
        assert!(unknown_service.snapshots.saved.lock().unwrap().is_empty());

        let (incompatible_service, command) = fixture();
        incompatible_service.evidence()[0]
            .source_candidate
            .candidate
            .answer = NormalizedAnswer::Selections(vec!["Z".to_owned()]);
        assert!(
            incompatible_service
                .import(command)
                .await
                .unwrap()
                .is_empty()
        );
        assert!(
            incompatible_service
                .snapshots
                .saved
                .lock()
                .unwrap()
                .is_empty()
        );
    }

    #[tokio::test]
    async fn foreign_or_ambiguous_bindings_fail_without_persistence() {
        let (service, mut command) = fixture();
        command.task_id = TaskId::new();
        assert!(matches!(
            service.import(command).await,
            Err(LocalAnswerCacheError::QuestionSnapshotNotFound)
        ));

        let (mut ambiguous_service, command) = fixture();
        let mut duplicate = ambiguous_service.snapshots.snapshot.questions[0].clone();
        duplicate.id = QuestionId::new();
        duplicate.remote_question_id = Some("target-question-2".to_owned());
        duplicate.position = 2;
        ambiguous_service
            .snapshots
            .snapshot
            .questions
            .push(duplicate);
        assert!(matches!(
            ambiguous_service.import(command).await,
            Err(LocalAnswerCacheError::EvidenceInvalid)
        ));
        assert!(ambiguous_service.snapshots.saved.lock().unwrap().is_empty());
    }

    impl LocalAnswerCacheService<FakeRepository> {
        fn evidence(&self) -> std::sync::MutexGuard<'_, Vec<PriorAnswerEvidence>> {
            self.snapshots.evidence.lock().unwrap()
        }
    }

    fn fixture() -> (
        LocalAnswerCacheService<FakeRepository>,
        ImportLocalAnswerCandidatesCommand,
    ) {
        let owner_id = UserId::new();
        let task_id = TaskId::new();
        let snapshot_id = QuestionSnapshotId::new();
        let target_question = question(task_id, "target-question", 1);
        let mut source_question = target_question.clone();
        source_question.id = QuestionId::new();
        source_question.remote_question_id = Some("source-question".to_owned());
        source_question.position = 7;
        let source_snapshot_id = QuestionSnapshotId::new();
        let source_candidate = AnswerCandidateRecord {
            id: AnswerCandidateId::new(),
            question_snapshot_id: source_snapshot_id,
            candidate: AnswerCandidate {
                question_id: source_question.id,
                source: AnswerSource::Manual,
                answer: NormalizedAnswer::Selections(vec!["A".to_owned()]),
                confidence: Some(AnswerConfidence::try_new(9_000).unwrap()),
                explanation: Some("Reviewed source evidence".to_owned()),
                provenance_sanitized: serde_json::json!({"origin": "manual_input"}),
            },
            created_at: Utc::now(),
        };
        let fingerprint = target_question.content_fingerprint().unwrap();
        let snapshot = QuestionSnapshot {
            id: snapshot_id,
            task_id,
            provider_id: ProviderId::new("provider-alpha").unwrap(),
            provider_version: "1.0.0".to_owned(),
            captured_at: Utc::now(),
            questions: vec![target_question],
            groups: Vec::new(),
        };
        (
            LocalAnswerCacheService::new(FakeRepository {
                owner_id,
                snapshot,
                evidence: Mutex::new(vec![PriorAnswerEvidence {
                    question_content_fingerprint: fingerprint,
                    source_question,
                    source_candidate,
                }]),
                existing: Mutex::new(Vec::new()),
                saved: Mutex::new(Vec::new()),
            }),
            ImportLocalAnswerCandidatesCommand {
                owner_id,
                task_id,
                question_snapshot_id: snapshot_id,
            },
        )
    }

    fn question(task_id: TaskId, remote_question_id: &str, position: u32) -> Question {
        Question {
            id: QuestionId::new(),
            task_id,
            remote_question_id: Some(remote_question_id.to_owned()),
            kind: QuestionKind::SingleChoice,
            stem: "Exact cache match".to_owned(),
            options: vec![
                QuestionOption {
                    id: "A".to_owned(),
                    content: Some("First".to_owned()),
                    attachments: Vec::new(),
                    metadata_sanitized: serde_json::json!({}),
                },
                QuestionOption {
                    id: "B".to_owned(),
                    content: Some("Second".to_owned()),
                    attachments: Vec::new(),
                    metadata_sanitized: serde_json::json!({}),
                },
            ],
            attachments: Vec::new(),
            metadata_sanitized: serde_json::json!({"page_kind": "work_preview"}),
            position,
        }
    }
}
