[package]
name = "asterismd"
description = "Asterism orchestration service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
asterism-api = { path = "../../crates/api" }
asterism-config = { path = "../../crates/config" }
asterism-domain = { path = "../../crates/domain" }
asterism-engine = { path = "../../crates/engine" }
asterism-events = { path = "../../crates/events" }
asterism-networking = { path = "../../crates/networking" }
asterism-provider-chaoxing = { path = "../../providers/chaoxing" }
asterism-provider-welearn = { path = "../../providers/welearn" }
asterism-provider-api = { path = "../../crates/provider-api" }
asterism-scheduler = { path = "../../crates/scheduler" }
asterism-secrets = { path = "../../crates/secrets" }
asterism-storage = { path = "../../crates/storage" }
axum.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
